services:
  ssh-655.cyrhades.fr:
    container_name: ssh-655
    build:
      context: ./.docker/ssh
      args:
        LANGUAGE: ${LANGUAGE:-fr}
    labels:
      ho.ctf.cyrhades: "challenge"
      ho.ctf.cyrhades.webssh: "1"
    environment:
      SSH_HOSTNAME: "ssh-655.cyrhades.fr"
      SSH_PORT: 22
      SSH_USERNAME: "cyrhades"
      SSH_PASSWORD: "secret"
    restart: unless-stopped
  spidersaurus.cyrhades.fr:
    image: anssi/fcsc2026-pwn-spidersaurus:latest
